config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root  'web_collections#index'
  get   '/about',     to: 'web_collections#about'
  get   '/new',       to: 'web_collections#new'
  post  '/new',       to: 'web_collections#create'
  resources :web_collections, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/collection.rb
class Collection < ApplicationRecord
  before_save { self.url = url.downcase }
  mount_uploader :image, ImageUploader
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, length: { maximum: 255 },
                  uniqueness:  { case_sensitive: false }
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable,
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/web_collections_controller.rb
class WebCollectionsController < ApplicationController
  before_action :user_signed_in?, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @collections = Collection.all
  end

  def about
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    if @collection.save
      flash[:success] = "collection を追加"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @collection = Collection.find(params[:id])
  end

  def update
    @collection = Collection.find(params[:id])
    if @collection.update(collection_params)
      flash[:success] = "collection を変更"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    Collection.find(params[:id]).destroy
    flash[:success] = "Collection deleted"
    redirect_to root_url
  end

  private
    
    def collection_params
      params.require(:collection).permit(:title, :url, :image)
    end

    def admin_user
      if !current_user&.admin?
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "Web Collection"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/web_collections_helper.rb
module WebCollectionsHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <%= link_to "WebCollections.com", root_path, class: "text-white" %>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  <!-- Font Awesome -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
  />
  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
  />
  <!-- MDB -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.css"
    rel="stylesheet"
  />
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to "WEBCOLLECTION", root_path, class: "navbar-brand" %>
          <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav  ms-auto">
              <li class="nav-item">
                <%= link_to "About", about_path, class: "nav-link" %>
              </li>
              <% if current_user&.admin? %>
                <li class="nav-item">
                  <%= link_to "New", new_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>

  <!-- MDB -->
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.js">
  </script>

</html>

app/views/shared/_error_messages.html.erb
<% if @collection.errors.any? %>
  <div class="alert alert-danger"> 
    
    <p><%= @collection.errors.count %>つのエラー</p>
    
    <ul>
    <% @collection.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/web_collections/about.html.erb
<% provide(:title, "About") %>
<h1>WebCollections#about</h1>
<p>Find me in app/views/web_collections/about.html.erb</p>

app/views/web_collections/edit.html.erb
<% provide(:title, "Edit") %>
<h1>WebCollections#edit</h1>

  <%= form_with(model: @collection, url: web_collection_path, local: true) do |f| %>

    <%= render 'shared/error_messages' %>

    <div class="form-outline mb-4">
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :title, class: 'form-label' %>
    </div>
  
    <div class="form-outline mb-4">
      <%= f.url_field :url, class: 'form-control' %>
      <%= f.label :url, class: 'form-label' %>
    </div>

    <%= f.label :image, class: 'form-label' %>
    <div class="form-outline mb-4">
      <%= f.file_field :image, accept: 'image/jpg,image/jpeg,image/gif,image/png', 
                               id: 'customFile', class: 'form-control' %>
    </div>
      
      <%= f.submit 'Save', class: 'btn btn-primary btn-block mb-4' %>
  <% end %>

app/views/web_collections/index.html.erb
<h1>WebCollections#index</h1>
<div class="container">
  <div class="row text-center">
    <% @collections.each do |collection| %>
      <div class="col-6 col-sm-4">
        <%= link_to image_tag(collection.image.url, width: "100%"), collection.url if collection.image? %>
        <%= link_to collection.title, web_collection_path(collection) %>
      </div>
    <% end %>
  </div>
</div>

app/views/web_collections/new.html.erb
<% provide(:title, "New") %>
<h1>WebCollections#new</h1>

  <%= form_with(model: @collection, url: new_path, local: true) do |f| %>

    <%= render 'shared/error_messages' %>

    <div class="form-outline mb-4">
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :title, class: 'form-label' %>
    </div>
  
    <div class="form-outline mb-4">
      <%= f.url_field :url, class: 'form-control' %>
      <%= f.label :url, class: 'form-label' %>
    </div>

    <%= f.label :image, class: 'form-label' %>
    <div class="form-outline mb-4">
      <%= f.file_field :image, accept: 'image/jpg,image/jpeg,image/gif,image/png',
                               id: 'customFile', class: 'form-control' %>
    </div>
      
      <%= f.submit 'Save', class: 'btn btn-primary btn-block mb-4' %>
  <% end %>

app/views/web_collections/show.html.erb
<% provide(:title, @collection.title) %>
<h1>WebCollections#show</h1>
<%= @collection.title %>,
<%= @collection.url %>
<%= link_to image_tag(@collection.image.url, width: "50%"), @collection.url if @collection.image? %>
<% if current_user&.admin? %>
  <%= button_to "", web_collection_path(@collection), method: :delete, class: "fas fa-trash" %>
<% end %>